// Auto-generated by scripts/generate-ai-manifest.mjs. Do not edit by hand.
export type AIEntry = { group: "chatgpt" | "codex"; label: string; href: string; tooltip: string; createdAtISO: string; slug: string; };
export const manifest = {
  "chatgpt": [
    {
      "group": "chatgpt",
      "label": "Pong",
      "href": "/extra/ai-generated/chatgpt/pong",
      "tooltip": "AI fever dream about Pong",
      "createdAtISO": "2025-03-06T18:18:07+01:00",
      "slug": "pong"
    },
    {
      "group": "chatgpt",
      "label": "Shitty Space Invaders",
      "href": "/extra/ai-generated/chatgpt/shitty-space-invaders",
      "tooltip": "AI fever dream about Shitty Space Invaders",
      "createdAtISO": "2025-04-14T10:56:03+02:00",
      "slug": "shitty-space-invaders"
    }
  ],
  "codex": [
    {
      "group": "codex",
      "label": "Contact",
      "href": "/extra/ai-generated/codex/contact",
      "tooltip": "AI fever dream about Contact",
      "createdAtISO": "2025-08-04T12:52:56+02:00",
      "slug": "contact"
    },
    {
      "group": "codex",
      "label": "Random Comments Page",
      "href": "/extra/ai-generated/codex/random-comments-page",
      "tooltip": "AI fever dream about Random Comments Page",
      "createdAtISO": "2025-08-22T14:25:10+02:00",
      "slug": "random-comments-page"
    },
    {
      "group": "codex",
      "label": "Testimonials",
      "href": "/extra/ai-generated/codex/testimonials",
      "tooltip": "AI fever dream about Testimonials",
      "createdAtISO": "2025-07-31T16:42:42+02:00",
      "slug": "testimonials"
    },
    {
      "group": "codex",
      "label": "Tinder for Horses",
      "href": "/extra/ai-generated/codex/tinder-for-horses",
      "tooltip": "AI fever dream about Tinder for Horses",
      "createdAtISO": "2025-07-31T17:17:24+02:00",
      "slug": "tinder-for-horses"
    }
  ],
  "techdemos": [
    {
      "group": "codex",
      "label": "Web Tech Demo 1",
      "href": "/extra/ai-generated/codex/web-tech-demo-1",
      "tooltip": "AI fever dream about Web Tech Demo 1",
      "createdAtISO": "2025-08-18T16:34:12+02:00",
      "slug": "web-tech-demo-1"
    },
    {
      "group": "codex",
      "label": "Web Tech Demo 1 V2",
      "href": "/extra/ai-generated/codex/web-tech-demo-1-v2",
      "tooltip": "AI fever dream about Web Tech Demo 1 V2",
      "createdAtISO": "2025-08-18T16:34:12+02:00",
      "slug": "web-tech-demo-1-v2"
    },
    {
      "group": "codex",
      "label": "Web Tech Demo 2",
      "href": "/extra/ai-generated/codex/web-tech-demo-2",
      "tooltip": "AI fever dream about Web Tech Demo 2",
      "createdAtISO": "2025-08-18T16:34:12+02:00",
      "slug": "web-tech-demo-2"
    },
    {
      "group": "codex",
      "label": "Web Tech Demo 3",
      "href": "/extra/ai-generated/codex/web-tech-demo-3",
      "tooltip": "AI fever dream about Web Tech Demo 3",
      "createdAtISO": "2025-08-19T10:14:13+02:00",
      "slug": "web-tech-demo-3"
    },
    {
      "group": "codex",
      "label": "Cli Tech Demo 2",
      "href": "/extra/ai-generated/codex/cli-tech-demo-2",
      "tooltip": "AI fever dream about Cli Tech Demo 2",
      "createdAtISO": "2025-08-18T17:13:31+02:00",
      "slug": "cli-tech-demo-2"
    },
    {
      "group": "codex",
      "label": "Cli Tech Demo 3",
      "href": "/extra/ai-generated/codex/cli-tech-demo-3",
      "tooltip": "AI fever dream about Cli Tech Demo 3",
      "createdAtISO": "2025-08-19T10:10:23+02:00",
      "slug": "cli-tech-demo-3"
    }
  ]
} as { chatgpt: AIEntry[]; codex: AIEntry[]; techdemos: AIEntry[] };
