export type Horse = {
  name: string;
  age: number;
  breed: string;
  location: string;
  gender: "Mare" | "Stallion" | "Gelding";
  heightCm: number; // height at withers in cm
  color: string;
  temperament: string; // e.g., Calm, Energetic
  disciplines: string[]; // e.g., trail, dressage, jumping
  description: string;
  interests: string[];
  image: string;
  photos?: string[]; // optional gallery, primary first
};

export const horses: Horse[] = [
  {
    name: "Star",
    age: 5,
    breed: "Arabian",
    location: "Sunny Valley",
    gender: "Mare",
    heightCm: 150,
    color: "Chestnut",
    temperament: "Energetic",
    disciplines: ["trail", "endurance"],
    description: "An energetic Arabian with a love for adventure.",
    interests: ["trail rides", "racing", "apple picking"],
    image: "https://images.unsplash.com/uploads/14136148007774dc82563/ce92d553?w=500&h=350&fit=crop",
  },
  {
    name: "Willow",
    age: 7,
    breed: "Morgan",
    location: "Seaside Ranch",
    gender: "Mare",
    heightCm: 148,
    color: "Bay",
    temperament: "Calm",
    disciplines: ["trail", "pleasure"],
    description: "Gentle mare that enjoys long rides on the beach.",
    interests: ["beach trots", "sunsets", "carrots"],
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=500&h=350&fit=crop",
  },
  {
    name: "Thunder",
    age: 4,
    breed: "Quarter Horse",
    location: "Rolling Plains",
    gender: "Gelding",
    heightCm: 156,
    color: "Sorrel",
    temperament: "Forward",
    disciplines: ["barrels", "ranch"],
    description: "Young stallion looking for fun and fast gallops.",
    interests: ["sprints", "mud baths", "hay bales"],
    image: "https://images.unsplash.com/photo-1504310977373-186d29f99322?w=500&h=350&fit=crop",
  },
  {
    name: "Bella",
    age: 6,
    breed: "Mustang",
    location: "Green Meadow",
    gender: "Mare",
    heightCm: 150,
    color: "Dun",
    temperament: "Curious",
    disciplines: ["trail", "liberty"],
    description: "Friendly and curious. Loves apples and cuddles.",
    interests: ["cuddles", "apple treats", "grooming"],
    image: "https://images.unsplash.com/photo-1514861889637-9f51bc99fc19?w=500&h=350&fit=crop",
  },
  {
    name: "Shadow",
    age: 8,
    breed: "Friesian",
    location: "Moonlit Ridge",
    gender: "Stallion",
    heightCm: 165,
    color: "Black",
    temperament: "Proud",
    disciplines: ["dressage", "driving"],
    description: "Mysterious Friesian that loves moonlit trots.",
    interests: ["night rides", "classical music", "pumpkin spice"],
    image: "https://images.unsplash.com/photo-1598974357801-cbca100e65d3?w=500&h=350&fit=crop",
  },
  {
    name: "Luna",
    age: 9,
    breed: "Andalusian",
    location: "Whispering Pines",
    gender: "Mare",
    heightCm: 160,
    color: "Grey",
    temperament: "Soft",
    disciplines: ["dressage", "trail"],
    description: "Elegant mare who enjoys quiet forest paths.",
    interests: ["forest walks", "stargazing", "sugar cubes"],
    image: "https://images.unsplash.com/photo-1593179449458-e0d43d512551?w=500&h=350&fit=crop",
  },
  {
    name: "Blaze",
    age: 5,
    breed: "Thoroughbred",
    location: "Highland Track",
    gender: "Gelding",
    heightCm: 163,
    color: "Bay",
    temperament: "Hot",
    disciplines: ["jumping", "eventing"],
    description: "Fiery spirit with a need for speed.",
    interests: ["jumping", "racing", "peppermints"],
    image: "https://images.unsplash.com/photo-1557374800-8ba4ccd60e9d?w=500&h=350&fit=crop",
  },
  {
    name: "Daisy",
    age: 6,
    breed: "Shetland Pony",
    location: "Kids' Corner Farm",
    gender: "Mare",
    heightCm: 104,
    color: "Piebald",
    temperament: "Sweet",
    disciplines: ["leadline", "cart"],
    description: "Sweet pony that loves children and sugar cubes.",
    interests: ["kids", "cart rides", "rolling in grass"],
    image: "https://images.unsplash.com/photo-1513966007261-5a86a5284471?w=500&h=350&fit=crop",
  },
  {
    name: "Marlin",
    age: 8,
    breed: "Quarter Horse",
    location: "Riverbend Trail",
    gender: "Gelding",
    heightCm: 158,
    color: "Buckskin",
    temperament: "Patient",
    disciplines: ["trail", "packing"],
    description: "Trail‑wise gelding who waits quietly while you cast. Steady over water crossings with a sense of humor.",
    interests: ["fly fishing", "river crossings", "campfires", "apple slices"],
    image: "/TFH/horse_holding_a_fish.png",
  },
  {
    name: "Flex",
    age: 6,
    breed: "Warmblood",
    location: "Iron Hoof Gym",
    gender: "Gelding",
    heightCm: 165,
    color: "Bay",
    temperament: "Motivated",
    disciplines: ["gymkhana", "jumping"],
    description: "Gym‑rat gelding who never skips leg day. Loves cardio laps and plyo poles.",
    interests: ["treadmills", "pole work", "protein cubes", "carrot shakes"],
    image: "/TFH/horse_in_a_gym.png",
  },
  {
    name: "Trailblazer",
    age: 9,
    breed: "Mustang",
    location: "Alpine Ridge",
    gender: "Mare",
    heightCm: 155,
    color: "Bay",
    temperament: "Sure‑footed",
    disciplines: ["trail", "endurance"],
    description: "Mountain‑wise mare who thrives on long hikes and scenic routes. Calm in traffic, confident over rocks and streams.",
    interests: ["switchbacks", "river crossings", "camping", "salt licks"],
    image: "/TFH/horse_on_a_hike.png",
  },
  {
    name: "DJ Gallop",
    age: 7,
    breed: "Dutch Warmblood",
    location: "Neon Pasture Club",
    gender: "Gelding",
    heightCm: 164,
    color: "Dark Bay",
    temperament: "Life of the party",
    disciplines: ["freestyle", "dressage"],
    description:
      "Turns every paddock into a dance floor. Balanced, rhythmic, and always on beat — perfect tempo for pirouettes and party tricks.",
    interests: ["late‑night canters", "glow sticks", "carrot mocktails", "bass drops"],
    image: "/TFH/horse_partying.png",
  },
  {
    name: "Solara",
    age: 8,
    breed: "Andalusian",
    location: "Costa del Sol, Spain",
    gender: "Mare",
    heightCm: 158,
    color: "Palomino",
    temperament: "Laid‑back",
    disciplines: ["trail", "dressage"],
    description:
      "Sun‑kissed beach cruiser with a silky mane and a love for splashy canters in the surf. Sure‑footed on coastal paths and happiest chasing sunsets.",
    interests: ["beach trots", "sea breeze", "palm shade", "salt licks", "sunsets"],
    image: "/TFH/horse_on_beach_holiday_south_europe.png",
  },
];
